// FreshFruit - Product & Category Data

const CATEGORIES = [
  {
    id: 'viet-nam',
    name: 'Trái cây Việt Nam',
    icon: '🇻🇳',
    count: 42,
    image: 'https://images.unsplash.com/photo-1601493700631-2b16ec4b4716?w=400&h=300&fit=crop&auto=format&q=80',
    color: 'bg-green-50',
  },
  {
    id: 'nhap-khau',
    name: 'Trái cây nhập khẩu',
    icon: '✈️',
    count: 28,
    image: 'https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?w=400&h=300&fit=crop&auto=format&q=80',
    color: 'bg-red-50',
  },
  {
    id: 'theo-mua',
    name: 'Theo mùa',
    icon: '🌿',
    count: 15,
    image: 'https://images.unsplash.com/photo-1537640538966-79f369143f8f?w=400&h=300&fit=crop&auto=format&q=80',
    color: 'bg-purple-50',
  },
  {
    id: 'hop-qua',
    name: 'Hộp quà trái cây',
    icon: '🎁',
    count: 12,
    image: 'https://images.unsplash.com/photo-1619566636858-adf3ef46400b?w=400&h=300&fit=crop&auto=format&q=80',
    color: 'bg-yellow-50',
  },
  {
    id: 'kho-gia',
    name: 'Khô - Sấy',
    icon: '🍂',
    count: 20,
    image: 'https://images.unsplash.com/photo-1528825871115-3581a5387919?w=400&h=300&fit=crop&auto=format&q=80',
    color: 'bg-orange-50',
  },
];

const PRODUCTS = [
  {
    id: 1,
    name: 'Táo Fuji Nhật Bản',
    slug: 'tao-fuji-nhat-ban',
    category: 'nhap-khau',
    tags: ['ban-chay', 'nhap-khau'],
    price: 185000,
    originalPrice: 220000,
    unit: 'kg',
    image: 'https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?w=600&h=600&fit=crop&auto=format&q=80',
    rating: 4.9,
    reviews: 284,
    badge: 'Bán chạy',
    badgeColor: 'bg-red-500',
    origin: 'Nhật Bản',
    description: 'Táo Fuji nhập khẩu trực tiếp từ Nhật Bản, vỏ đỏ đẹp, thịt giòn ngọt, thơm đặc trưng.',
    inStock: true,
    isNew: false,
    isPromo: true,
  },
  {
    id: 2,
    name: 'Cam Sành Việt Nam',
    slug: 'cam-sanh-viet-nam',
    category: 'viet-nam',
    tags: ['ban-chay', 'viet-nam'],
    price: 45000,
    originalPrice: null,
    unit: 'kg',
    image: 'https://images.unsplash.com/photo-1582979512210-99b6a53386f9?w=600&h=600&fit=crop&auto=format&q=80',
    rating: 4.8,
    reviews: 512,
    badge: 'VietGAP',
    badgeColor: 'bg-green-600',
    origin: 'Vĩnh Long',
    description: 'Cam sành Vĩnh Long ngọt thanh, nhiều nước, giàu vitamin C. Thu hoạch mỗi sáng.',
    inStock: true,
    isNew: false,
    isPromo: false,
  },
  {
    id: 3,
    name: 'Nho Xanh Mỹ',
    slug: 'nho-xanh-my',
    category: 'nhap-khau',
    tags: ['nhap-khau', 'moi'],
    price: 320000,
    originalPrice: 380000,
    unit: 'kg',
    image: 'https://images.unsplash.com/photo-1537640538966-79f369143f8f?w=600&h=600&fit=crop&auto=format&q=80',
    rating: 4.7,
    reviews: 189,
    badge: 'Mới về',
    badgeColor: 'bg-blue-500',
    origin: 'Mỹ',
    description: 'Nho xanh không hạt nhập khẩu từ California, trái to mọng, ngọt tự nhiên.',
    inStock: true,
    isNew: true,
    isPromo: true,
  },
  {
    id: 4,
    name: 'Dâu Tây Đà Lạt',
    slug: 'dau-tay-da-lat',
    category: 'viet-nam',
    tags: ['ban-chay', 'viet-nam'],
    price: 120000,
    originalPrice: 150000,
    unit: 'hộp 500g',
    image: 'https://images.unsplash.com/photo-1464965911861-746a04b4bca6?w=600&h=600&fit=crop&auto=format&q=80',
    rating: 4.9,
    reviews: 643,
    badge: 'Hot',
    badgeColor: 'bg-red-500',
    origin: 'Đà Lạt',
    description: 'Dâu tây Đà Lạt tươi, trái đỏ mọng, thơm ngọt chua dịu. Hái buổi sáng, giao trong ngày.',
    inStock: true,
    isNew: false,
    isPromo: true,
  },
  {
    id: 5,
    name: 'Xoài Cát Hòa Lộc',
    slug: 'xoai-cat-hoa-loc',
    category: 'viet-nam',
    tags: ['viet-nam', 'theo-mua'],
    price: 85000,
    originalPrice: null,
    unit: 'kg',
    image: 'https://images.unsplash.com/photo-1601493700631-2b16ec4b4716?w=600&h=600&fit=crop&auto=format&q=80',
    rating: 4.8,
    reviews: 325,
    badge: 'Đặc sản',
    badgeColor: 'bg-yellow-500',
    origin: 'Tiền Giang',
    description: 'Xoài cát Hòa Lộc đặc sản Tiền Giang, thịt vàng đậm, không xơ, ngọt thơm đặc trưng.',
    inStock: true,
    isNew: false,
    isPromo: false,
  },
  {
    id: 6,
    name: 'Sầu Riêng Monthong',
    slug: 'sau-rieng-monthong',
    category: 'nhap-khau',
    tags: ['ban-chay', 'nhap-khau'],
    price: 180000,
    originalPrice: 220000,
    unit: 'kg',
    image: 'https://images.unsplash.com/photo-1528825871115-3581a5387919?w=600&h=600&fit=crop&auto=format&q=80',
    rating: 4.6,
    reviews: 421,
    badge: 'Bán chạy',
    badgeColor: 'bg-red-500',
    origin: 'Thái Lan',
    description: 'Sầu riêng Monthong Thái Lan cơm vàng dày, hạt lép, béo thơm đặc trưng. Chín tự nhiên.',
    inStock: true,
    isNew: false,
    isPromo: true,
  },
  {
    id: 7,
    name: 'Bơ 034 Đắk Lắk',
    slug: 'bo-034-dak-lak',
    category: 'viet-nam',
    tags: ['viet-nam', 'moi'],
    price: 65000,
    originalPrice: null,
    unit: 'kg',
    image: 'https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?w=600&h=600&fit=crop&auto=format&q=80',
    rating: 4.7,
    reviews: 278,
    badge: 'Hữu cơ',
    badgeColor: 'bg-green-600',
    origin: 'Đắk Lắk',
    description: 'Bơ 034 Đắk Lắk trái to, cơm vàng béo ngậy, không xơ, giàu chất dinh dưỡng.',
    inStock: true,
    isNew: true,
    isPromo: false,
  },
  {
    id: 8,
    name: 'Kiwi Vàng New Zealand',
    slug: 'kiwi-vang-new-zealand',
    category: 'nhap-khau',
    tags: ['nhap-khau', 'moi'],
    price: 280000,
    originalPrice: 350000,
    unit: 'hộp 6 trái',
    image: 'https://images.unsplash.com/photo-1585059895524-72359e06133a?w=600&h=600&fit=crop&auto=format&q=80',
    rating: 4.8,
    reviews: 196,
    badge: 'Nhập khẩu',
    badgeColor: 'bg-blue-500',
    origin: 'New Zealand',
    description: 'Kiwi vàng Zespri từ New Zealand, ngọt dịu hơn kiwi xanh, giàu vitamin C và K.',
    inStock: true,
    isNew: true,
    isPromo: true,
  },
  {
    id: 9,
    name: 'Cherry Mỹ Đỏ',
    slug: 'cherry-my-do',
    category: 'nhap-khau',
    tags: ['nhap-khau', 'ban-chay'],
    price: 450000,
    originalPrice: 520000,
    unit: 'hộp 500g',
    image: 'https://images.unsplash.com/photo-1528821128474-27f963b062bf?w=600&h=600&fit=crop&auto=format&q=80',
    rating: 4.9,
    reviews: 387,
    badge: 'Premium',
    badgeColor: 'bg-purple-600',
    origin: 'Mỹ',
    description: 'Cherry đỏ nhập khẩu từ Washington, trái to căng mọng, vị ngọt đậm, ít chua.',
    inStock: true,
    isNew: false,
    isPromo: true,
  },
  {
    id: 10,
    name: 'Dưa Lưới Nhật Bản',
    slug: 'dua-luoi-nhat-ban',
    category: 'nhap-khau',
    tags: ['nhap-khau', 'moi'],
    price: 380000,
    originalPrice: null,
    unit: 'trái',
    image: 'https://images.unsplash.com/photo-1571575173700-afb9492e6a50?w=600&h=600&fit=crop&auto=format&q=80',
    rating: 4.7,
    reviews: 143,
    badge: 'Cao cấp',
    badgeColor: 'bg-amber-500',
    origin: 'Nhật Bản',
    description: 'Dưa lưới Nhật cao cấp, thịt cam đẹp, ngọt thơm mịn màng. Quà tặng sang trọng.',
    inStock: true,
    isNew: true,
    isPromo: false,
  },
  {
    id: 11,
    name: 'Thanh Long Ruột Đỏ',
    slug: 'thanh-long-ruot-do',
    category: 'viet-nam',
    tags: ['viet-nam'],
    price: 38000,
    originalPrice: null,
    unit: 'kg',
    image: 'https://images.unsplash.com/photo-1527325678964-54921661f888?w=600&h=600&fit=crop&auto=format&q=80',
    rating: 4.6,
    reviews: 298,
    badge: 'VietGAP',
    badgeColor: 'bg-green-600',
    origin: 'Bình Thuận',
    description: 'Thanh long ruột đỏ Bình Thuận, ngọt nhẹ, giàu chất chống oxy hóa, đẹp da.',
    inStock: true,
    isNew: false,
    isPromo: false,
  },
  {
    id: 12,
    name: 'Lê Hàn Quốc',
    slug: 'le-han-quoc',
    category: 'nhap-khau',
    tags: ['nhap-khau'],
    price: 195000,
    originalPrice: 240000,
    unit: 'hộp 4 trái',
    image: 'https://images.unsplash.com/photo-1514756331096-242fdeb70d4a?w=600&h=600&fit=crop&auto=format&q=80',
    rating: 4.8,
    reviews: 231,
    badge: 'Nhập khẩu',
    badgeColor: 'bg-blue-500',
    origin: 'Hàn Quốc',
    description: 'Lê Hàn Quốc trái lớn, giòn ngọt, nhiều nước, thơm thanh. Hộp quà lý tưởng.',
    inStock: true,
    isNew: false,
    isPromo: true,
  },
];

const TESTIMONIALS = [
  {
    id: 1,
    name: 'Nguyễn Thị Lan',
    role: 'Khách hàng thân thiết',
    avatar: 'https://i.pravatar.cc/100?img=1',
    rating: 5,
    comment: 'Trái cây ở đây luôn tươi và ngon. Tôi đặt hàng gần như mỗi tuần và chưa bao giờ thất vọng. Giao hàng nhanh, đóng gói cẩn thận. Rất hài lòng!',
    date: '2024-09-15',
  },
  {
    id: 2,
    name: 'Trần Văn Minh',
    role: 'Khách hàng mới',
    avatar: 'https://i.pravatar.cc/100?img=3',
    rating: 5,
    comment: 'Lần đầu đặt thử hộp trái cây nhập khẩu, quá tuyệt vời! Cherry và nho Mỹ ngon không thua gì mua ở siêu thị mà giá lại hợp lý hơn nhiều.',
    date: '2024-09-18',
  },
  {
    id: 3,
    name: 'Phạm Thu Hương',
    role: 'Khách hàng thân thiết',
    avatar: 'https://i.pravatar.cc/100?img=5',
    rating: 5,
    comment: 'Dâu tây Đà Lạt tươi ơi là tươi! Đặt lúc 8h sáng, 9h đã có hàng rồi. Chất lượng trái cây rất đồng đều, không có trái nào bị dập hay hư.',
    date: '2024-09-20',
  },
  {
    id: 4,
    name: 'Lê Hoàng Nam',
    role: 'Chủ doanh nghiệp',
    avatar: 'https://i.pravatar.cc/100?img=8',
    rating: 5,
    comment: 'Công ty tôi thường xuyên đặt hộp quà trái cây cho đối tác. FreshFruit luôn đảm bảo chất lượng và giao đúng hẹn. Rất chuyên nghiệp và đáng tin cậy!',
    date: '2024-09-22',
  },
];

// Normalize product properties for cross-component compatibility
PRODUCTS.forEach(p => {
  p.reviewCount = p.reviews || p.reviewCount || 0;
  p.isFeatured = p.isFeatured !== undefined ? p.isFeatured : (p.tags && p.tags.includes('ban-chay'));
  p.isBestSeller = p.isBestSeller !== undefined ? p.isBestSeller : (p.tags && p.tags.includes('ban-chay'));
  p.discount = p.originalPrice ? Math.round((1 - p.price / p.originalPrice) * 100) : (p.discount || 0);
  p.images = p.images || [p.image, p.image];
  p.stock = p.stock || (p.inStock ? 50 : 0);
});

// Helper Functions
function getProductBySlug(slug) {
  return PRODUCTS.find(p => p.slug === slug || String(p.id) === String(slug)) || null;
}

function getProductById(id) {
  return PRODUCTS.find(p => String(p.id) === String(id) || p.slug === id) || null;
}

function getProductsByCategory(catId) {
  if (!catId || catId === 'all') return PRODUCTS;
  return PRODUCTS.filter(p => p.category === catId);
}

function formatPrice(amount) {
  if (amount === undefined || amount === null) return '0đ';
  return new Intl.NumberFormat('vi-VN', { style: 'currency', currency: 'VND' }).format(amount).replace('₫', 'đ');
}

function renderStars(rating) {
  let html = '';
  for (let i = 1; i <= 5; i++) {
    if (i <= Math.floor(rating)) html += '<i class="fas fa-star text-yellow-400 text-xs"></i>';
    else if (i - 0.5 <= rating) html += '<i class="fas fa-star-half-alt text-yellow-400 text-xs"></i>';
    else html += '<i class="far fa-star text-yellow-400 text-xs"></i>';
  }
  return html;
}

